Materials = 
DISTINCT(
    UNION(
        SELECTCOLUMNS(
            FILTER(DatExpStatus_Motor, NOT(ISBLANK(DatExpStatus_Motor[MaterialName]))),
            "MaterialName", DatExpStatus_Motor[MaterialName]
        ),
        SELECTCOLUMNS(
            FILTER(DatExpStatus_Temperature, NOT(ISBLANK(DatExpStatus_Temperature[MaterialName]))),
            "MaterialName", DatExpStatus_Temperature[MaterialName]
        ),
        SELECTCOLUMNS(
            FILTER(DatExpStatus_Power, NOT(ISBLANK(DatExpStatus_Power[MaterialName]))),
            "MaterialName", DatExpStatus_Power[MaterialName]
        ),
        SELECTCOLUMNS(
            FILTER(DatExpStatus_Pressure, NOT(ISBLANK(DatExpStatus_Pressure[MaterialName]))),
            "MaterialName", DatExpStatus_Pressure[MaterialName]
        )
    )
)
